update testdata to resolve the testdata issue

diff --git a/.github/workflows/run-e2e-tests.yml b/.github/workflows/run-e2e-tests.yml
--- a/.github/workflows/run-e2e-tests.yml
+++ b/.github/workflows/run-e2e-tests.yml
@@ -95,11 +95,11 @@ jobs:
 
           echo "Running Pytest-BDD tests"
           pytest --junitxml=output/test-results.xml
-          EXIT_CODE=$?
-
-          if [ "$EXIT_CODE" -ne 0 ]; then
-            echo "::error::Pytest failed with exit code $EXIT_CODE"
-            exit $EXIT_CODE  
+          if [ $? -ne 0 ]; then
+            echo "Pytest-BDD tests failed"
+            exit 1
+          else
+            echo "Pytest-BDD tests passed"
           fi
       
       - name: Publish test results to GitHub UI
@@ -109,6 +109,5 @@ jobs:
           name: BDD Test Summary
           path: '**/output/test-results.xml'
           reporter: java-junit
-          fail-on-error: false
 
 
